{{- range .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
type: {{ .type }}
data:
{{- range $key, $value := .data }}
  {{- if eq $key ".dockerconfigjson" }}
  {{ $key }}: {{ $value }}
  {{- else }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}
---
{{- end }}